planning_scene_monitor_options:
  name: "planning_scene_monitor"
  robot_description: "robot_description"
  joint_state_topic: "/joint_states"
  attached_collision_object_topic: "/planning_scene_monitor"
  publish_planning_scene_topic: "/publish_planning_scene"
  monitored_planning_scene_topic: "/monitored_planning_scene"
  wait_for_initial_state_timeout: 10.0

planning_scene_monitor:
  publish_geometry_updates: true
  publish_planning_scene: true
  publish_planning_scene_hz: 10.0
  publish_state_updates: true
  publish_transforms_updates: true  

planning_pipelines:
  pipeline_names:
    - ompl

plan_request_params:
  planning_attempts: 1
  planning_pipeline: ompl
  max_velocity_scaling_factor: 1.0
  max_acceleration_scaling_factor: 1.0